// tests generated by Claude
// import * as dotenv from 'dotenv';
import * as path from 'path';

// Load .env from project root (3 levels up from tests folder)
const envPath = path.resolve(__dirname, '../../../.env');
console.log('📁 Looking for .env at:', envPath);
// dotenv.config({ path: envPath });

// Now import walletService
import { walletService } from '../walletService';
import { ethers } from 'ethers';

console.log('🔑 API Key loaded:', process.env.ETHERSCAN_API_KEY ? 'YES ✓' : 'NO ✗');
console.log('🔑 First 5 chars:', process.env.ETHERSCAN_API_KEY?.substring(0, 5) || 'MISSING');
console.log('');

async function testWallet() {
  console.log('=== Testing Wallet Service ===\n');

  try {
    // 1. Initialize provider
    console.log('1. Initializing provider...');
    await walletService.initializeProvider();
    console.log('✓ Provider initialized\n');

    // 2. Create new wallet
    console.log('2. Creating new wallet...');
    const newWallet = await walletService.walletCreate();
    console.log('✓ Wallet created:');
    console.log('Address:', newWallet.address);
    console.log('Seed Phrase:', newWallet.phrase);
    console.log('Private Key:', newWallet.privKey);
    console.log('⚠️  SAVE THESE - They won\'t be stored!\n');

    // 3. Check balance
    console.log('3. Checking balance...');
    const balance = await walletService.getWalletBalance(newWallet.address);
    console.log('✓ Balance:', balance, 'ETH\n');

    // 4. Get Transactions
    console.log('4. Getting transaction history...\n');

    console.log('4a. Testing with known active address (WETH contract)...');
    const activeAddress = '0xbd4d5b8475bcb71e06a65224ccfd6e8f2e6c6279';
    let transactions = await walletService.walletTransactHistory(activeAddress);
    console.log('   API returned:', transactions?.length || 0, 'transactions');

    if (transactions && transactions.length > 0) {
      console.log('   ✓ SUCCESS! Sample transaction:');
      console.log('     Hash:', transactions[0].hash);
      console.log('     Block:', transactions[0].blockNumber);
      console.log('     From:', transactions[0].from.substring(0, 10) + '...');
      console.log('     To:', transactions[0].to?.substring(0, 10) + '...');
      console.log('     Value:', ethers.formatEther(transactions[0].value), 'ETH');
    } else {
      console.log('   ⚠️  WARNING: No transactions found for active address');
      console.log('   This might indicate the API key is not working properly\n');
    }

    // 5. Get ETH price
    console.log('5. Getting current ETH price...');
    const ethPrice = await walletService.getCurrETHPrice();
    console.log('✓ ETH Price: $', ethPrice, '\n');

    // 6. Estimate gas fee (example)
    console.log('6. Estimating gas fee for 0.001 ETH transfer...');
    const gasFee = await walletService.estimateGasFee(
      '0x12C937c6E4F52C965b3984A97ccb82AC5B692158', // random address
      '0.001'
    );
    console.log('✓ Estimated Gas Fee:');
    console.log('  ETH:', gasFee.eth);
    console.log('  USD: $', gasFee.usd, '\n');

    // 7. Reconnect with seed phrase
    console.log('7. Reconnecting wallet with seed phrase...');
    const reconnectedAddress = await walletService.walletConnect(newWallet.phrase);
    console.log('✓ Reconnected to:', reconnectedAddress);
    console.log('Match:', reconnectedAddress === newWallet.address ? '✓' : '✗', '\n');

  } catch (error) {
    console.error('❌ Error:', error);
  }
}

testWallet();