// tests generated by Claude
import { walletService } from '../walletService';
import { ethers } from 'ethers';

console.log('🔑 API Key loaded:', process.env.ETHERSCAN_API_KEY ? 'YES ✓' : 'NO ✗');
console.log('🔑 First 5 chars:', process.env.ETHERSCAN_API_KEY?.substring(0, 5) || 'MISSING');
console.log('');

async function testWallet() {
  console.log('=== Testing Wallet Service ===\n');

  try {
    // 1. Initialize provider
    console.log('1. Initializing provider...');
    await walletService.initializeProvider();
    console.log('✓ Provider initialized\n');

    // 2. Create new wallet
    console.log('2. Creating new wallet...');
    const newWallet = await walletService.walletCreate();
    console.log('✓ Wallet created:');
    console.log('Address:', newWallet.address);
    console.log('Seed Phrase:', newWallet.phrase);
    console.log('Private Key:', newWallet.privKey);
    console.log('⚠️  SAVE THESE - They won\'t be stored!\n');

    // 3. Check balance
    console.log('3. Checking balance...');
    const balance = await walletService.getWalletBalance(newWallet.address);
    console.log('✓ Balance:', balance, 'ETH\n');

    // 4. Get ETH price
    console.log('4. Getting current ETH price...');
    const ethPrice = await walletService.getCurrETHPrice();
    console.log('✓ ETH Price: $', ethPrice, '\n');

    // 5. Estimate gas fee (example)
    console.log('5. Estimating gas fee for 0.001 ETH transfer...');
    const gasFee = await walletService.estimateGasFee(
      '0x12C937c6E4F52C965b3984A97ccb82AC5B692158', // random address
      '0.001'
    );
    console.log('✓ Estimated Gas Fee:');
    console.log('  ETH:', gasFee.eth);
    console.log('  USD: $', gasFee.usd, '\n');

    // 6. Reconnect with seed phrase
    console.log('6. Reconnecting wallet with seed phrase...');
    const reconnectedAddress = await walletService.walletConnect(newWallet.phrase);
    console.log('✓ Reconnected to:', reconnectedAddress);
    console.log('Match:', reconnectedAddress === newWallet.address ? '✓' : '✗', '\n');

  } catch (error) {
    console.error('❌ Error:', error);
  }
}

testWallet();